### ISSUE TITLE
Pesquisa no Protocolo Integrado não está considerando as aspas

### ISSUE THREAD

**Issue by pedrohpms** [pengovbr/mod-sei-protocolo-integrado#25]
**Descreva o erro**
--
Ao realizar pesquisa no Protocolo Integrado, quando esta pesquisa trata de termo com mais de uma palavra, o sistema está retornando todas as ocorrências de qualquer uma das palavras, independente do termo ter sido colocado entre aspas.

Para fins de testes, busquei por "Pedro Henrique" (entre aspas) e o Protocolo Integrado retornou resultados para "Pedro Henrique", apenas "Pedro" e apenas "Henrique".
___

**Para reproduzir**
--
Passos para reproduzir o comportamento:

> 1. Vá para https://protocolointegrado.gov.br/.
> 2. No campo "Consultar Documentos", digite um termo de pesquisa com duas palavras ou mais, entre aspas.
> 3. Clique no ícone de pesquisa.
> 4. Veja o erro.

____

**Comportamento esperado**
--
_Uma descrição clara e concisa do que você esperava que acontecesse._

No exemplo em tela, que o sistema exibisse apenas as ocorrências do termo "Pedro Henrique". Ou seja, que na execução da busca, o sistema leve em conta os caracteres de organização como aspas, sinais de mais e menos, operadores "e" e "ou". Não sendo possível aplicar os demais critérios, que **pelo menos** seja aplicada a especificação dos termos entre aspas.

___

**Screenshots**
--
Ao buscar por "Pedro Henrique", os resultados incluem:

![image](https://github.com/supergovbr/mod-sei-protocolo-integrado/assets/79460464/ecb080ae-aae5-4cd5-984b-e677c2ee97ff)

e

![image](https://github.com/supergovbr/mod-sei-protocolo-integrado/assets/79460464/1b03a866-1536-47e6-a8d2-423dca9e71a9)

Na primeira imagem, não há ocorrência do termo "Henrique" e na segunda, do termo "Pedro".

___

**Contexto da falha (Por favor, complete a seguinte informação):**
--
 - Versão do sistema: Protocolo Integrado (em produção)
 - Navegador: Google Chrome
 - Perfil do Usuário: Usuário básico (o comportamento persiste, estando o usuário logado ou não)
 - Banco de Dados: 

___

**Informações adicionais**
--
Para maiores detalhes sobre a solicitação, tratar com a PO do Protocolo Integrado, @duanequintino.

**Comment by duanequintino** [comment]
Não sendo possível aplicar os demais critérios, que pelo menos seja aplicada a especificação dos termos entre aspas.

**Comment by Paneque2** [comment]
Atividade ja está em produção.
