### ISSUE TITLE
Função depreciada: ereg_replace

### ISSUE THREAD

**Issue by jefersongoliveira** [pengovbr/mod-sei-protocolo-integrado#27]
**Descreva o erro**
A função ereg_replace localizada no arquivo web/modulos/protocolo_integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php se tornou depreciada nas versões atuais do php. Sendo necessária sua substituição por função equivalente.

-----

**Para reproduzir**
O erro foi reportado no log

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: 3.3.0
 - Perfil do Usuário: administrador
 - Banco de Dados: PostgreSQL

-----
**Log de Erros**
`Agendamento FALHOU (vplseidpv01.mte.br)

Servidor: vplseidpv01.mte.br

Data/Hora: 29/08/2023 07:30:03

Comando: ProtocoloIntegradoAgendamentoRN::publicarProtocoloIntegrado()

Erro: Descrição:
Error: Call to undefined function ereg_replace() in /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php:1003
Stack trace:
#0 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(979): ProtocoloIntegradoMonitoramentoProcessosRN->validarCPF('085.044.418-73')
#1 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(794): ProtocoloIntegradoMonitoramentoProcessosRN->gerarNomeInteressadoComCpfEscondido('OLGA MARIA PARR...')
#2 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(132): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosMonitorados(Array)
#3 /opt/infra/infra_php/InfraRN.php(151): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosConectado(Object(ProtocoloIntegradoParametrosDTO))
#4 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoAgendamentoRN.php(32): InfraRN->__call('publicarProcess...', Array)
#5 /opt/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(664): ProtocoloIntegradoAgendamentoRN->publicarProtocoloIntegrado(Array)
#6 /opt/infra/infra_php/InfraAgendamentoTarefa.php(218): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#7 /opt/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('naoresponda@tra...', 'naoresponda@tra...')
#8 {main}

Mensagem:
Call to undefined function ereg_replace()

Trilha de Processamento:
#0 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(979): ProtocoloIntegradoMonitoramentoProcessosRN->validarCPF('085.044.418-73')
#1 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(794): ProtocoloIntegradoMonitoramentoProcessosRN->gerarNomeInteressadoComCpfEscondido('OLGA MARIA PARR...')
#2 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(132): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosMonitorados(Array)
#3 /opt/infra/infra_php/InfraRN.php(151): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosConectado(Object(ProtocoloIntegradoParametrosDTO))
#4 /opt/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoAgendamentoRN.php(32): InfraRN->__call('publicarProcess...', Array)
#5 /opt/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(664): ProtocoloIntegradoAgendamentoRN->publicarProtocoloIntegrado(Array)
#6 /opt/infra/infra_php/InfraAgendamentoTarefa.php(218): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#7 /opt/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('naoresponda@tra...', 'naoresponda@tra...')
#8 {main}`

**Comment by caduvieira** [comment]
Duplicado #22
