### ISSUE TITLE
Erro ao tentar instalar versão mais recente do módulo do Protocolo Integrado

### ISSUE THREAD

**Issue by mateussbh** [pengovbr/mod-sei-protocolo-integrado#38]
**Descreva o erro**
Usuário reporta erro ao tentar instalar versão mais recente do módulo.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
Comece instalando a versão 2.0.1. Para depois ir atualizando as versões, passando pela 2.1.x, até chegar na 3.0.1, para certificar que o arquivo de script de atualização de versões está completo.

Começar tentando simular o erro apresentado, para depois atualizar os arquivos que fazem a atualização de versão na instalação, e garantir que não teve algum gap de versões no arquivo de atualização de versões.

-----

**Comportamento esperado**
Ao final, o usuário deverá conseguir instalar a última versão independente de qual versão ele esteja.

-----

**Screenshots**
Print do erro:
![WhatsApp Image 2024-02-07 at 14 30 52](https://github.com/pengovbr/mod-sei-protocolo-integrado/assets/3789823/405b9684-cb0f-4b52-bf8e-0771b0a03915)

-----

**Comment by mateussbh** [comment]
Evidência do teste:

https://mtegovbr.sharepoint.com/:v:/s/Super.br/ER1qLnazSVpGvfPOQ6QQK7kBIAysaQyOa2k09z5uYD5-qw?e=a1XS0o

**Comment by amelquia** [comment]
@duanequintino  a issue encontra-se disponível para validação do P.O.

**Comment by amelquia** [comment]
09/05/2024
@duanequintino  foi realizada a pré-release da issue.  Agora, é necessário que você realize a validação, por favor.
