### ISSUE TITLE
Compatibilidade com SEi 4.1.1

### ISSUE THREAD

**Issue by mateussbh** [pengovbr/mod-sei-protocolo-integrado#43]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Faz-se necessário corrigir o teste automatizado do projeto, para que este rode no SEI versão 4.1.1.

**Comment by yurioliveiramgi** [comment]
Validado por: https://github.com/pengovbr/mod-sei-protocolo-integrado/commit/ba9f2b25afd9975c5c2166c262a18e951e79d460
