### ISSUE TITLE
Remover configurações SELF-SIGNED das chamadas de webservices dos módulos

### ISSUE THREAD

**Issue by guilhermeadc** [pengovbr/mod-sei-protocolo-integrado#7]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema. Ex. Sempre fico frustrado quando [...]

-----

**Descreva a solução que você gostaria**
Revisar todos os módulos para remover as configurações que permita chamadas de webservices sem segurança por aceitar certificados auto-assinados no servidor da API.

-----

**Descreva alternativas que você considerou**
Uma descrição clara e concisa de quaisquer soluções ou recursos alternativos que você considerou.

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by Mauro1706** [comment]
Tarefa que foi realizada a correção em outro modulo https://github.com/supergovbr/mod-sei-pen/issues/188

**Comment by MatheusMarques80** [comment]
Pull request: https://github.com/supergovbr/mod-sei-protocolo-integrado/pull/13
